### ISSUE TITLE
Sensor detected but UUID unrecognized

### ISSUE THREAD

**Issue by ajaybhargav** [floe/BTLE#12]
I ported your library on a PIC micro. And I am testing it on iPad using nRF MCP and nRF Temp. I can see my sensor pushing data to BLE in Master control panel. MCP showing sensordata as <0x1809>:<value> But Service UUID is shown as N/A. nRF temp is not able to detect my sensor altogether. Is it something wrong with the iPad application for not recognizing 0x1809 as a valid UUID for temperature?

Screenshot:
![img_0138](https://cloud.githubusercontent.com/assets/927133/15943967/f8124c12-2ea8-11e6-9cd8-d5fa16c23e8a.PNG)

**Comment by floe** [comment]
Hard to tell for sure from the picture alone; can you post the entire packet you're sending as hex data?
