### ISSUE TITLE
Why am i getting this error?

### ISSUE THREAD

**Issue by Milap7** [floe/BTLE#13]
`In member function 'void BTLE::begin(const char*)':
'class RF24' has no member named 'setAddressWidth'
 radio->setAddressWidth(4);
`

**Comment by floe** [comment]
See README: `You will also need to install the RF24 library installable either from the Arduino IDE or https://github.com/TMRh20/RF24 .` It's possible that the "official" version has been modified, try the TMRh20 version.

**Comment by Milap7** [comment]
It works! Thanks.
