### ISSUE TITLE
Estimote

### ISSUE THREAD

**Issue by arroyoht** [floe/BTLE#14]
I am not being able to detect estimote beacons. From where I am, it is detecting some random MAC adresses, but the beacon I am trying to detect is not showing up on the receiver example. 
This is the type of beacon http://estimote.com/

**Comment by floe** [comment]
IIRC the Estimote is iBeacon-compatible. That means they're broadcasting a full 16-byte UUID. The nRF24L01+ can only receive packets with at most ~24 bytes of payload, and if the beacon broadcasts anything else (signal strength, name, ...) then the packet will become too long. If you have a way to edit the beacon's name, try shortening it to something like 'a' and see if it will be received. But in general, this is a hardware limitation of the nRF24L01+.
