### ISSUE TITLE
How can i set/change nrf24l01 UUID? Can it support Eddystone?

### ISSUE THREAD

**Issue by Milap7** [floe/BTLE#15]

**Comment by floe** [comment]
You might fit a single UUID into the payload, but not in a format that's compatible to iBeacon (too large). Eddystone might work, if the URL is short enough.

**Comment by Milap7** [comment]
What is the syntax to set uuid? Can you give a code example? That would be very helpful.

**Comment by floe** [comment]
I've never tried this, so no ready-made example. You will probably have to remove the part in BTLE.cpp that sets the "complete name", and add the UUID as raw binary data.
