### ISSUE TITLE
function reversing to_nRF_Float(float t)

### ISSUE THREAD

**Issue by crash007** [floe/BTLE#19]
Hi,

I would like to parse the temperature received for GATT service 0x1809 as used by to_nRF_Float.
Is it possible to add a function that reverses to_nRF_Float, for example nRF_int32_to_Float or something. 

I have a working snippet in javascript if it could help.

```
function getTemp(data) {
    var unsigned = unsignedToSigned(parseInt(data[0]) + (parseInt(data[1]) << 8) + (parseInt(data[2]) << 16), 24);
    var tmp = unsigned.toString(16);
    var sign = data[3] & 0b10000000; //Blir antingen 0 eller 128
    exp = -sign + (data[3] & 0b01111111);
    let temp = unsigned * Math.pow(10, exp);
    // console.log(temp);
    return temp;
};

function unsignedToSigned(unsigned, size) {
    if ((unsigned & (1 << size - 1)) != 0) {
        unsigned = -1 * ((1 << size - 1) - (unsigned & ((1 << size - 1) - 1)));
    }
    return unsigned;
}

```

**Comment by floe** [comment]
Don't have time to implement this myself at the moment, sorry - but feel free to send a pull request. Shouldn't be too hard to convert this into C (in particular, `var tmp` is unused anyway).

**Comment by crash007** [comment]
I realised it was very simple when i had a positive int. Just shift the bits
