### ISSUE TITLE
window / door sensor

### ISSUE THREAD

**Issue by evilknivel** [floe/BTLE#23]
Hi,

and first thank you for this beautiful library!

Is it possible so get it working as an door / window sensor?

**Comment by floe** [comment]
Not sure what you mean. On its own, the library can only control a nRF24L01+ chip to send and receive Bluetooth LE advertisements. You'll need to add a) an actual sensor to detect the window state and b) code to make it send something once the sensor is triggered.

**Comment by evilknivel** [comment]
Hi ohh sorry maybe i make it not totally clear what i mean. I thought the function of an ble device is declared by the service UUID so that other devices can recognize ist als such. Or am i wrong?

**Comment by floe** [comment]
Ah, now I get it. Yes, you're right, but AFAICT there's no UUID for door/window sensor. The full list is at https://btprodspecificationrefs.blob.core.windows.net/assigned-values/16-bit%20UUID%20Numbers%20Document.pdf - I've found 
"GATT Service - 0x183B - Binary Sensor" which might be somewhat suitable, but using the full GATT protocol won't work with the bare nRF24L01+ device, you would need a dedicated BTLE transceiver for that (e.g. something based on the nRF51/52).

**Comment by evilknivel** [comment]
Ahh okay, vielen Dank, dass Sie sich die Zeit genommen haben, um zu antworten!
