### ISSUE TITLE
error while compiling 'send' example after install BTLE

### ISSUE THREAD

**Issue by chau-ba-thong** [floe/BTLE#25]
hi, guys
I install BTLE ver 1.0.0 (and RF24 already used) , but when compling exanple 'send' from BTLE, i got error:
Multiple libraries were found for "RF24.h", and 
Multiple libraries were found for "BTLE.h"
any idea about that error?

**Comment by floe** [comment]
I would assume that this is an issue with your Arduino library installation and not necessarily one with this library here. Do you get the same error when you compile one of the RF24 examples?

**Comment by chau-ba-thong** [comment]
No, i have used rf24 lib before install btle, and had some projects with
nrf24l01 , all ok. Error just happened after install btle.h. Any conflict?
My ide is 1.8.1

**Comment by chau-ba-thong** [comment]
dear Floe,
could you give me the link to download RF24.zip, the lib which you are using with this BTLE lib? I think I will remove my RF24 lib, reinstall your rf24 lib and try to test again. maybe i can find something to solve this problem.
BTW i attache the error nessage
[error_message.txt](https://github.com/floe/BTLE/files/7081744/error_message.txt)

**Comment by floe** [comment]
The last time I tested this was quite a few years ago, so probably with v1.2.0 of RF24: https://github.com/nRF24/RF24/archive/refs/tags/RF24v1.2.0.zip (perhaps also v1.3.0 or v1.3.1, see https://github.com/nRF24/RF24/releases?after=v1.3.5).

**Comment by chau-ba-thong** [comment]
Thanks, I'll check it out.

**Comment by chau-ba-thong** [comment]
the problem maybe in the new ver of RF24! i reinstall the RF24 ver 1.3.4 and there is no more error message when compile the send example, and i think i will close this issue.
thanks a lot
