### ISSUE TITLE
Support for NRF52x devices?

### ISSUE THREAD

**Issue by TMRh20** [floe/BTLE#28]
First off please excuse my ignorance when it comes to Bluetooth, but would there be any practicality in supporting NRF52x devices?

I know they natively support Bluetooth, but when using the https://github.com/TMRh20/nrf_to_nrf driver, which uses the RF24 API and the ESB protocol, it would require minor changes and this might allow users to switch easily between using Bluetooth and ESB. Just wondering about this and if there might be any interest since the NRF52x actually supports Bluetooth and large packet sizes. Or is this a dumb idea since we can use BLE directly?

**Comment by floe** [comment]
I think you're off waaay better if you use the BLE features of the nRF5x series directly (also applies to the nRF51). See https://github.com/floe/BLEPeripheralObserver for a somewhat dated Arduino example.
