### ISSUE TITLE
What data is contained in the payload using recv file?

### ISSUE THREAD

**Issue by hm50** [floe/BTLE#8]
Hello Florian! Awesome stuff!
I have implemented this with no issues using an arduino uno and the nrf24l01. I am hoping to use this to catch ble tags. The only info I need from the tag is major and minor. Are those contained within the packets of hex I am receiving from my ble tags? Or what does that payload contain? 

I thank you in advance for your time.

Thank you!
Harvey

**Comment by floe** [comment]
The nRF24L01+ only can receive up to 16 bytes of data after the address, so a full iBeacon message won't fit in there, in particular major and minor number will be cut off. You'll only be able to see part of the UUID... (see also https://en.wikipedia.org/wiki/IBeacon#Technical_details).
