### ISSUE TITLE
Is it possible to catch data from smartphone?

### ISSUE THREAD

**Issue by Jatsekku** [floe/BTLE#9]
As in topic. I would like to send data from my smartphone to nrf24l01, but when I program the device with rec example it is inivisible for my phone, with other examples it works. Is there any "big" documentation for it?

**Comment by floe** [comment]
Sorry, there's no proper documentation. In general, it's possible to send data from your phone to the nRF24L01, however, keep in mind that you can receive at most ~ 20 bytes. If the broadcast message is longer, then it will not be received at all. So there's not a lot of room besides the phone's name.

**Comment by Jatsekku** [comment]
Could you send me any example? Thats amunt of data its still sufficient for
my purpose. Thank you :)
16 kwi 2016 20:11, "Florian Echtler" <notifications@github.com> napisał(a):

**Comment by floe** [comment]
Are you working on Android? Then, if you have a phone where the feature is enabled, you could try an app like "Locate Beacon" and see if the `recv` example can pick that up.
